version: "3.9"

services:

  go:
    container_name: urlshorter_go
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis

  pg:
    container_name: urlshorter_pg
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./app/migrations/0001_create_url_table.sql:/docker-entrypoint-initdb.d/0001_create_url_table.sql
      - ./data/pg:/var/lib/postgresql/data
    depends_on:
      - redis

  redis:
    container_name: urlshorter_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - ./data/redis:/data