version: "3.9"

services:

  go:
    container_name: urlshorter_go
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pg
    links:
      - pg
      - redis

  pg:
    container_name: urlshorter_pg
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    depends_on:
      - redis

  redis:
    container_name: urlshorter_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - ./data/redis:/data